
language: node_js
node_js:
  - 16
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - cd udagram-api-feed && docker build -t udagram-api-feed .
  - docker tag udagram-api-feed collinsoden/udagram-api-feed:v1 && cd ..
  - cd udagram-api-user && docker build -t udagram-api-user .
  - docker tag udagram-api-user collinsoden/udagram-api-user:v1 && cd ..
  - cd udagram-frontend && docker build -t udagram-frontend .
  - docker tag udagram-frontend collinsoden/udagram-frontend:v1 && cd ..
  - cd udagram-reverseproxy && docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy collinsoden/udagram-reverseproxy:v1 && cd ..
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push collinsoden/udagram-api-feed:v1
  - docker push collinsoden/udagram-api-user:v1
  - docker push collinsoden/udagram-frontend:v1
  - docker push collinsoden/udagram-reverseproxy:v1
